// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsaL3kco0jmwGd9b_c7LlNHvXjl1p0d3A',
    appId: '1:343480193164:web:ddcce00c7fbcc7ac65aba9',
    messagingSenderId: '343480193164',
    projectId: 'sgtm-backend',
    authDomain: 'sgtm-backend.firebaseapp.com',
    storageBucket: 'sgtm-backend.firebasestorage.app',
    measurementId: 'G-D8TSK04NN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs5YraTu-lCo2CjyP0B1NqtlZ8-KXkkfI',
    appId: '1:343480193164:android:0c38f9250393873065aba9',
    messagingSenderId: '343480193164',
    projectId: 'sgtm-backend',
    storageBucket: 'sgtm-backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGXTCflhati-P88lZsan3MjoP6OZSUzRc',
    appId: '1:343480193164:ios:b6a4ff62f29b437265aba9',
    messagingSenderId: '343480193164',
    projectId: 'sgtm-backend',
    storageBucket: 'sgtm-backend.firebasestorage.app',
    iosBundleId: 'com.example.scheduleGenAndTimeManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGXTCflhati-P88lZsan3MjoP6OZSUzRc',
    appId: '1:343480193164:ios:b6a4ff62f29b437265aba9',
    messagingSenderId: '343480193164',
    projectId: 'sgtm-backend',
    storageBucket: 'sgtm-backend.firebasestorage.app',
    iosBundleId: 'com.example.scheduleGenAndTimeManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsaL3kco0jmwGd9b_c7LlNHvXjl1p0d3A',
    appId: '1:343480193164:web:980b0f2b927fa5fb65aba9',
    messagingSenderId: '343480193164',
    projectId: 'sgtm-backend',
    authDomain: 'sgtm-backend.firebaseapp.com',
    storageBucket: 'sgtm-backend.firebasestorage.app',
    measurementId: 'G-0EEWP61DXE',
  );
}
