import 'package:schedule_gen_and_time_management/src/pages/task%20manage%20tab/model/all_epic.dart';
import 'package:schedule_gen_and_time_management/src/pages/task%20manage%20tab/model/study_epic.dart';
import 'package:schedule_gen_and_time_management/src/pages/task%20manage%20tab/model/work_epic.dart';

List<AllEpic> allEpic = [
  StudyEpic(id: '01', name: 'Code flutter', desCription: 'Study flutter'),
  StudyEpic(id: '02', name: 'Code java', desCription: 'Study java'),
  StudyEpic(id: '03', name: 'Code python', desCription: 'Study python'),
  StudyEpic(id: '04', name: 'Code react', desCription: 'Study react '),
  StudyEpic(id: '05', name: 'Code C#', desCription: 'Study C#'),
  WorkEpic(id: '06', name: 'English Teacher', desCription: 'Lecturer'),
  WorkEpic(
      id: '07',
      name: 'International Customer Service Representative',
      desCription: 'International Customer Service Representative'),
  WorkEpic(id: '08', name: 'Import-Export Sales Staff', desCription: 'Import-Export Sales Staff'),
  WorkEpic(id: '09', name: 'International Tour Guide', desCription: 'International Tour Guide'),
  WorkEpic(id: '10', name: 'Translator', desCription: 'Interpreter'),
  WorkEpic(id: '11', name: 'Translator', desCription: 'Interpreter'),
  WorkEpic(id: '12', name: 'Translator', desCription: 'Interpreter'),
  WorkEpic(id: '13', name: 'Translator', desCription: 'Interpreter'),
  WorkEpic(id: '14', name: 'Translator', desCription: 'Interpreter'),
  WorkEpic(id: '15', name: 'Translator', desCription: 'Interpreter'),
  WorkEpic(id: '16', name: 'Translator', desCription: 'Interpreter'),
  WorkEpic(id: '17', name: 'Translator', desCription: 'Interpreter'),
  WorkEpic(id: '18', name: 'Translator', desCription: 'Interpreter'),
  WorkEpic(id: '19', name: 'Translator', desCription: 'Interpreter'),
  WorkEpic(id: '20', name: 'Translator', desCription: 'Interpreter'),
  WorkEpic(id: '21', name: 'Translator', desCription: 'Interpreter'),
  WorkEpic(id: '22', name: 'Translator', desCription: 'Interpreter'),
  WorkEpic(id: '23', name: 'Translator', desCription: 'Interpreter'),
  WorkEpic(id: '24', name: 'Translator', desCription: 'Interpreter'),
  WorkEpic(id: '20', name: 'Translator', desCription: 'Interpreter'),
  WorkEpic(id: '210', name: 'Translator', desCription: 'Interpreter'),
  WorkEpic(id: '310', name: 'Translator', desCription: 'Interpreter'),
  WorkEpic(id: '410', name: 'Translator', desCription: 'Interpreter'),
  WorkEpic(id: '510', name: 'Translator', desCription: 'Interpreter'),
  WorkEpic(id: '610', name: 'Translator', desCription: 'Interpreter'),
  WorkEpic(id: '710', name: 'Translator', desCription: 'Interpreter'),
  WorkEpic(id: '810', name: 'Translator', desCription: 'Interpreter'),
  WorkEpic(id: '910', name: 'Translator', desCription: 'Interpreter'),
  WorkEpic(id: '110', name: 'Translator', desCription: 'Interpreter'),
];
